var data = {
    "publications":
    [
        // {
        //     "highlight": true,
        //     "img": "",
        //     "title": "",
        //     "authors": "",
        //     "conference": "",
        //     "year": ,
        //     "arxiv": "",
        //     "github": "",
        // },
       {
           "highlight": true,
           "img": "images_output/tcsvt_grmvs.png",
           "title": "Learning Multi-View Stereo with Geometry-Aware Prior",
           "authors": "Kehua Chen, Zhenlong Yuan, Haihong Xiao, Tianlu Mao, Zhaoqi Wang",
           "journal": "IEEE Transactions on Circuits and Systems for Video Technology (<b>IEEE Trans. TCSVT, IF:11.1</b>)",
           "year": 2025,
           "pdf": "https://ieeexplore.ieee.org/document/11029471",
        },
        {
            "highlight": true,
            "img": "images_output/tcsvt_ssc.png",
            "title": "	Semantic Scene Completion via Semantic-aware Guidance and Interactive Refinement Transformer",
            "authors": "Haihong Xiao, Wenxiong Kang, Hao Liu, Yuqiong Li, Ying He",
            "journal": "IEEE Transactions on Circuits and Systems for Video Technology (<b>IEEE Trans. TCSVT, IF:11.1</b>)",
            "year": 2025,
            "pdf": "https://ieeexplore.ieee.org/document/10804191",
        },
        {
            "highlight": true,
            "img": "images_output/tcsvt_spv.png",
            "title": "Point Cloud Completion via Self-projected View Augmentation and Implicit Field Constraint",
            "authors": "Haihong Xiao, Ying He, Hao Liu, Wenxiong Kang, Yuqiong Li",
            "journal": "IEEE Transactions on Circuits and Systems for Video Technology (<b>IEEE Trans. TCSVT, IF:11.1</b>)",
            "year": 2024,
            "pdf": "https://ieeexplore.ieee.org/document/10589366",
        },
        {
            "highlight": true,
            "img": "images_output/tits_ssc.png",
            "title": "Instance-Aware Monocular 3D Semantic Scene Completion",
            "authors": "Haihong Xiao, Hongbin Xu, Wenxiong Kang, Yuqiong Li",
            "journal": "IEEE Transactions on Intelligent Transportation Systems (<b>IEEE Trans. TITS, IF:8.4</b>)",
            "year": 2024,
            "pdf": "https://ieeexplore.ieee.org/document/10379527",
        },
                
        {
            "highlight": true,
            "img": "images_output/tim_tfc.png",
            "title": "Text-Free Controllable 3-D Point Cloud Generation",
            "authors": "Haihong Xiao, Wenxiong Kang, Yuqiong Li, Hongbin Xu",
            "journal": "IEEE Transactions on Instrumentation and Measurement (<b>IEEE Trans. TIM, IF:5.9</b>)",
            "year": 2024,
            "pdf": "https://ieeexplore.ieee.org/document/10411836",
        },
        {
            "highlight": true,
            "img": "images_output/tcsvt_eamvs.png",
            "title": "EA-MVSNet: Learning Error-Awareness for Enhanced Multi-View Stereo",
            "authors": "Wencong Gu†, Haihong Xiao†, Xueyan Zhao, Wenxiong Kang",
            "journal": "IEEE Transactions on Circuits and Systems for Video Technology (<b>IEEE Trans. TCSVT, IF:11.1</b>)",
            "year": 2024,
            "pdf": "https://ieeexplore.ieee.org/document/10601197",
        },
        {
            "highlight": true,
            "img": "images_output/tmm_sdf.jpg",
            "title": "Tri2plane: Advancing Neural Implicit Surface Reconstruction for Indoor Scenes",
            "authors": "Yiping Xie†, Haihong Xiao†, Wenxiong Kang",
            "journal": "IEEE Transactions on Multimedia (<b>IEEE Trans. TMM, IF:9.7</b>)",
            "year": 2024,
            "pdf": "https://ieeexplore.ieee.org/document/10982030",
        },
        {
            "highlight": true,
            "img": "images_output/tcsvt_dmnet.png",
            "title": "Distinguishing and Matching-Aware Unsupervised Point Cloud Completion",
            "authors": "Haihong Xiao, Yuqiong Li, Wenxiong Kang, Qiuxia Wu",
            "journal": "IEEE Transactions on Circuits and Systems for Video Technology (<b>IEEE Trans. TCSVT, IF:11.1</b>)",
            "year": 2023,
            "pdf": "https://ieeexplore.ieee.org/document/10056970",
        },
        {
            "highlight": true,
            "img": "images_output/tim_mdnet.png",
            "title": "Multi-Dimensional Graph Interactional Network for Progressive Point Cloud Completion",
            "authors": "Haihong Xiao, Hongbin Xu, Wenxiong Kang, Yuqiong Li",
            "journal": "IEEE Transactions on Instrumentation and Measurement (<b>IEEE Trans. TIM, IF:5.9</b>)",
            "year": 2023,
            "pdf": "https://ieeexplore.ieee.org/document/9978708",
        },
        {
            "highlight": true,
            "img": "images_output/iccv_pdc.jpg",
            "title": "PointDC: Unsupervised Semantic Segmentation of 3D Point Clouds via Cross-modal Distillation and Super-Voxel Clustering",
            "authors": "Zisheng Chen, Hongbin Xu, Weitao Chen, Zhipeng Zhou, Haihong Xiao, Baigui Sun, Xuansong Xie, Wenxiong Kang",
            "journal": "IEEE/CVF International Conference on Computer Vision (<b>ICCV, CCF A</b>)",
            "year": 2023,
            "pdf": "https://openaccess.thecvf.com/content/ICCV2023/html/Chen_PointDC_Unsupervised_Semantic_Segmentation_of_3D_Point_Clouds_via_Cross-Modal_ICCV_2023_paper.html",
            "github": "https://github.com/SCUT-BIP-Lab/PointDC",
        },
        {   
            "title": "Semi-supervised Deep Multi-view Stereo",
            "authors": "Hongbin Xu, Weitao Chen, Yang Liu, Zhipeng Zhou, Haihong Xiao, Baigui Sun, Xuansong Xie, Wenxiong Kang",
            "journal": "The 31st ACM International Conference on Multimedia (<b>ACM MM, CCF A</b>)",
            "year": 2023,
            // "oral": "Oral",
            "pdf": "https://arxiv.org/pdf/2207.11699",
        },
                {
                    "title": "Key techniques for three-dimensional completion: a review",
                    "authors": "Haihong Xiao, Qiuxia Wu, Yuqiong Li, Wenxiong Kang",
                    "journal": "Optics and Precision Engineering (<b>EI, T1</b>)",
                    "year": 2023,
                    // "oral": "Oral",
                    "pdf": "https://ope.lightpublishing.cn/zh/article/doi/10.37188/OPE.20233105.0667/",
                },
                {
                    "title": "Point cloud complementation method of Epipremnum aureum leaves under occlusion conditions based on MSF-PPD network",
                    "authors": "Haihong Xiao, Huanliang Xu, Shihang Ma, Ling Chen, Jiangbo Wang, Haoyun Wang",
                    "journal": "Trans. Chin. Soc. of Agric. Mach (<b>EI, T1</b>)",
                    "year": 2021,
                    // "oral": "Oral",
                    "pdf": "https://kns.cnki.net/kcms2/article/abstract?v=mdHrqfOh4rGUiwIS0kRH45ZYVWOvWTLH2_Vt9Z4ynTVwt8dZGLhDltZShZ7ZLvO9D9egBipkKL8AzJymuIlrVJiCHf0TAqAHb5YnNZaZO04j17llzH-FYR4oHt-gks5jOXGeUd5LDFNPv0eObpWfBdcHlQU4ZloUrdE2LIU2XAWTC4F8mqb00Q==&uniplatform=NZKPT&language=CHS",
                },
                {
                    "title": "Estimation Algorithm of Leaf Shape Parameters of Scirpus sibiricum Based on MRE-PointNet and Autoencoder Model",
                    "authors": "Haoyun Wang, Haihong Xiao, Shihang Ma, Lin Chen, Jiangbo Wang, Huanliang Xu",
                    "journal": "Trans. Chin. Soc. of Agric. Mach. (<b>EI, T1</b>)",
                    "year": 2021,
                    // "oral": "Oral",
                    "pdf": "https://kns.cnki.net/kcms2/article/abstract?v=mdHrqfOh4rHKBxdQCWO1lGBDxcnmV3q_ikJTZ653FuAri6bDVfB-E1Hk2XKjyxnz_rGCF_ldO5z__JIVe_1-mb4-PQ7jS_JZxYzHu4hFpFoqy4Sfv98xtHogHXp4Q1O9L1PaHvJ-XqvQ0LuVnWOItq-m7OQr5HQMwsGsonLHkD7I14AVTueyHg==&uniplatform=NZKPT&language=CHS",
                },
                {
                    "title": "Estimation of external phenotypic parameters of Bunting leaves using FL-DGCNN model",
                    "authors": "Ling Chen, Haoyun Wang, Haihong Xiao, Shihang Ma, Yao Yang, Huanliang Xu ",
                    "journal": "Trans. Chin. Soc. of Agric. Engin. (<b>EI, T1</b>)",
                    "year": 2021,
                    // "oral": "Oral",
                    "pdf": "https://kns.cnki.net/kcms2/article/abstract?v=mdHrqfOh4rGUiwIS0kRH45ZYVWOvWTLH2_Vt9Z4ynTVwt8dZGLhDllXI-aRfomIO0JEay4YYRoQFC9FSpeKje53rz25wTP1QxFZJY0R5aWbjaZOsqRiurs-FWg2gxX1LOkGykFD5ym2oU71w-HelYxTMuQ8RgfhhQCbvFD684Beh0c8UQ5x7hQ==&uniplatform=NZKPT&language=CHS",
                },
        {
            "highlight": true,
            "img": "images_output/tvcg_splaco.png",
            "title": "SplatCo: Structure-View Collaborative Gaussian Splatting for Detail-Preserving Rendering of Large-Scale Unbounded Scenes",
            "authors": "Haihong Xiao, Jianan Zou, Yuxin Zhou, Ying He, Wenxiong Kang",
            "conference": " ",
            "arxiv": "https://arxiv.org/abs/2505.17951",
            "year": 2025,
            "github": "https://github.com/SCUT-BIP-Lab/SplatCo",
        },
                {
                    "highlight": true,
                    "img": "images_output/tmm_geosp.png",
                    "title": "Geometry-Aware 3D Gaussian Representation for Real-Time Rendering of Large-Scale Scenes",
                    "authors": "Haihong Xiao, Jianan Zou, Shuai Xing, Pengcheng Li, Wenxiong Kang",
                    "conference": " ",
                    "year": 2025,
                    "github": "https://github.com/SCUT-BIP-Lab/Geo_gs",
                },
         {
             "title": "EA-3DGS: Efficient and Adaptive 3D Gaussians with Highly Enhanced Quality for outdoor scenes",
             "authors": "Jianlin Guo, Haihong Xiao, Wenxiong Kang",
             "conference": " ",
             "arxiv": "https://arxiv.org/abs/2505.10787",
             "year": 2025,
             "github": "https://github.com/SCUT-BIP-Lab/EA-3DGS",
         },
        {
            "title": "3D Scene Graph Guided Vision-Language Pre-training",
            "authors": "Hao Liu, Yanni Ma, Yan Liu, Haihong Xiao, Ying He",
            "year": 2024,
            "conference": " ",
            "arxiv": "https://arxiv.org/pdf/2411.18666",
            "github": "",
        },
        {
            "title": "Point Cloud Unsupervised Pre-training via 3D Gaussian Splatting",
            "authors": "Hao Liu, Minglin Chen, Yanni Ma, Haihong Xiao, Ying He",
            "year": 2024,
            "conference": " ",
            "arxiv": "https://arxiv.org/pdf/2411.18667",
            "github": "",
        }
    ],
    "fields":
    {
        "arxiv": "arxiv",
        "pdf": "PDF",
        "github": "Github",
    },
    "author_links":
    {
        "Haihong Xiao": "https://scholar.google.com/citations?user=8AV-HUYAAAAJ&hl=zh-CN"

    }
};