var data = {
    "publications":
    [
        // {
        //     "highlight": true,
        //     "img": "",
        //     "title": "",
        //     "authors": "",
        //     "conference": "",
        //     "year": ,
        //     "arxiv": "",
        //     "github": "",
        // },
       {
           "title": "Learning Multi-View Stereo with Geometry-Aware Prior",
           "authors": "Kehua Chen, Zhenlong Yuan, Haihong Xiao, Tianlu Mao, Zhaoqi Wang",
           "journal": "IEEE Transactions on Circuits and Systems for Video Technology (<b>IEEE Trans. TCSVT</b>)",
           "year": 2025,
           "pdf": "https://ieeexplore.ieee.org/document/11029471",
        },
        {
            "highlight": true,
            "img": "images_output/tcsvt_ssc.png",
            "title": "	Semantic Scene Completion via Semantic-aware Guidance and Interactive Refinement Transformer",
            "authors": "Haihong Xiao, Wenxiong Kang, Hao Liu, Yuqiong Li, Ying He",
            "journal": "IEEE Transactions on Circuits and Systems for Video Technology (<b>IEEE Trans. TCSVT</b>)",
            "year": 2025,
            "pdf": "https://ieeexplore.ieee.org/document/10804191",
        },
        {
            "highlight": true,
            "img": "images_output/tcsvt_spv.png",
            "title": "Point Cloud Completion via Self-projected View Augmentation and Implicit Field Constraint",
            "authors": "Haihong Xiao, Ying He, Hao Liu, Wenxiong Kang, Yuqiong Li",
            "journal": "IEEE Transactions on Circuits and Systems for Video Technology (<b>IEEE Trans. TCSVT</b>)",
            "year": 2024,
            "pdf": "https://ieeexplore.ieee.org/document/10589366",
        },
        {
            "highlight": true,
            "img": "images_output/tits_ssc.png",
            "title": "Instance-Aware Monocular 3D Semantic Scene Completion",
            "authors": "Haihong Xiao, Hongbin Xu, Wenxiong Kang, Yuqiong Li",
            "journal": "IEEE Transactions on Intelligent Transportation Systems (<b>IEEE Trans. TITS</b>)",
            "year": 2024,
            "pdf": "https://ieeexplore.ieee.org/document/10379527",
        },
                
        {
            "title": "Text-Free Controllable 3-D Point Cloud Generation",
            "authors": "Haihong Xiao, Wenxiong Kang, Yuqiong Li, Hongbin Xu",
            "journal": "IEEE Transactions on Instrumentation and Measurement (<b>IEEE Trans. TIM</b>)",
            "year": 2024,
            "pdf": "https://ieeexplore.ieee.org/document/10411836",
        },
        {
            "title": "EA-MVSNet: Learning Error-Awareness for Enhanced Multi-View Stereo",
            "authors": "Wencong Gu†, Haihong Xiao†, Xueyan Zhao, Wenxiong Kang",
            "journal": "IEEE Transactions on Circuits and Systems for Video Technology (<b>IEEE Trans. TCSVT</b>)",
            "year": 2024,
            "pdf": "https://ieeexplore.ieee.org/document/10601197",
        },
        {
            "title": "Tri2plane: Advancing Neural Implicit Surface Reconstruction for Indoor Scenes",
            "authors": "Yiping Xie†, Haihong Xiao†, Wenxiong Kang",
            "journal": "IEEE Transactions on Multimedia (<b>IEEE Trans. TMM</b>)",
            "year": 2024,
            "pdf": "https://ieeexplore.ieee.org/document/10982030",
        },
        {
            "highlight": true,
            "img": "images_output/tcsvt_dmnet.png",
            "title": "Distinguishing and Matching-Aware Unsupervised Point Cloud Completion",
            "authors": "Haihong Xiao, Yuqiong Li, Wenxiong Kang, Qiuxia Wu",
            "journal": "IEEE Transactions on Circuits and Systems for Video Technology (<b>IEEE Trans. TCSVT</b>)",
            "year": 2023,
            "pdf": "https://ieeexplore.ieee.org/document/10056970",
        },
        {
            "highlight": true,
            "img": "images_output/tim_mdnet.png",
            "title": "Multi-Dimensional Graph Interactional Network for Progressive Point Cloud Completion",
            "authors": "Haihong Xiao, Hongbin Xu, Wenxiong Kang, Yuqiong Li",
            "journal": "IEEE Transactions on Instrumentation and Measurement (<b>IEEE Trans. TIM</b>)",
            "year": 2023,
            "pdf": "https://ieeexplore.ieee.org/document/9978708",
        },
        {   
            "title": "PointDC: Unsupervised Semantic Segmentation of 3D Point Clouds via Cross-modal Distillation and Super-Voxel Clustering",
            "authors": "Zisheng Chen, Hongbin Xu, Weitao Chen, Zhipeng Zhou, Haihong Xiao, Baigui Sun, Xuansong Xie, Wenxiong Kang",
            "journal": "IEEE/CVF International Conference on Computer Vision (<b>CCF A, ICCV</b>)",
            "year": 2023,
            "pdf": "https://openaccess.thecvf.com/content/ICCV2023/html/Chen_PointDC_Unsupervised_Semantic_Segmentation_of_3D_Point_Clouds_via_Cross-Modal_ICCV_2023_paper.html",
            "github": "https://github.com/SCUT-BIP-Lab/PointDC",
        },
        {   
            "title": "Semi-supervised Deep Multi-view Stereo",
            "authors": "Hongbin Xu, Weitao Chen, Yang Liu, Zhipeng Zhou, Haihong Xiao, Baigui Sun, Xuansong Xie, Wenxiong Kang",
            "journal": "The 31st ACM International Conference on Multimedia (<b>CCF A, ACM MM</b>)",
            "year": 2023,
            // "oral": "Oral",
            "pdf": "https://arxiv.org/pdf/2207.11699",
        },
                {
                    "highlight": true,
                    "img": "images_output/tip_ssc.png",
                    "title": "Enhanced Geometry and Semantics for Camera-based 3D Semantic Scene Completion",
                    "authors": "Haihong Xiao, Wenxiong Kang, Yulan Guo, Hao Liu, Ying He",
                    "conference": "submitted to IEEE Transactions on Image Processing (<b>TIP</b>)",
                    "year": 2025,
                },
        {
            "highlight": true,
            "img": "images_output/tvcg_splaco.png",
            "title": "SplatCo: Structure-View Collaborative Gaussian Splatting for Detail-Preserving Rendering of Large-Scale Unbounded Scenes",
            "authors": "Haihong Xiao, Jianan Zou, Yuxin Zhou, Ying He, Wenxiong Kang",
            "conference": " ",
            "arxiv": "https://arxiv.org/abs/2505.17951",
            "year": 2025,
            "github": "https://github.com/SCUT-BIP-Lab/SplatCo",
        },
                {
                    "title": "Geometry-Aware 3D Gaussian Representation for Real-Time Rendering of Large-Scale Scenes",
                    "authors": "Haihong Xiao, Jianan Zou, Shuai Xing, Pengcheng Li, Wenxiong Kang",
                    "conference": "submitted to IEEE Transactions on Multimedia (<b>TMM</b>)",
                    "year": 2025,
                    "github": "https://github.com/SCUT-BIP-Lab/Geo_gs",
                },
         {
             "title": "EA-3DGS: Efficient and Adaptive 3D Gaussians with Highly Enhanced Quality for outdoor scenes",
             "authors": "Jianlin Guo, Haihong Xiao, Wenxiong Kang",
             "conference": " ",
             "arxiv": "https://arxiv.org/abs/2505.10787",
             "year": 2025,
             "github": "https://github.com/SCUT-BIP-Lab/EA-3DGS",
         },
        {
            "title": "3D Scene Graph Guided Vision-Language Pre-training",
            "authors": "Hao Liu, Yanni Ma, Yan Liu, Haihong Xiao, Ying He",
            "year": 2024,
            "conference": " ",
            "arxiv": "https://arxiv.org/pdf/2411.18666",
            "github": "",
        },
        {
            "title": "Point Cloud Unsupervised Pre-training via 3D Gaussian Splatting",
            "authors": "Hao Liu, Minglin Chen, Yanni Ma, Haihong Xiao, Ying He",
            "year": 2024,
            "conference": " ",
            "arxiv": "https://arxiv.org/pdf/2411.18667",
            "github": "",
        }
    ],
    "fields":
    {
        "arxiv": "arxiv",
        "pdf": "PDF",
        "github": "Github",
    },
    "author_links":
    {
        "Haihong Xiao": "https://scholar.google.com/citations?user=8AV-HUYAAAAJ&hl=zh-CN",
        "Wenxiong Kang": "https://www.scholat.com/auwxkang",
        "Ying He": "https://personal.ntu.edu.sg/yhe/",
        "Yulan Guo": "https://www.yulanguo.cn/",
        "Hao Liu": "https://scholar.google.com/citations?user=CEEtEnoAAAAJ&hl=zh-CN&oi=sra",
        "Hongbin Xu": "https://scholar.google.com/citations?user=mRC_emoAAAAJ&hl=zh-CN&oi=ao",
        "Qiuxia Wu": "https://scholar.google.com/citations?user=bzt_YKwAAAAJ&hl=zh-CN",
        "Xueyan Zhao": "https://yanzhao.scut.edu.cn/open/ExpertInfo.aspx?zjbh=l9fI4ICNGHU1YImPAbWlLQ==",
        "Tianlu Mao": "https://scholar.google.com/citations?user=851N-WEAAAAJ&hl=zh-CN&oi=ao",
        "Zhenlong Yuan": "https://scholar.google.com/citations?user=zii-mcAAAAAJ&hl=zh-CN&oi=ao",
        "Minglin Chen": "https://scholar.google.com/citations?user=G4oCNmUAAAAJ&hl=zh-CN&oi=sra",
        "Yanni Ma": "https://scholar.google.com/citations?user=jc58aTgAAAAJ&hl=zh-CN&oi=ao",
        "Zhaoqi Wang": "https://baike.baidu.com/item/%E7%8E%8B%E5%85%86%E5%85%B6/8059428",
        "Yuqiong Li": "https://people.ucas.ac.cn/~0047224"

    }
};